"use strict";
exports.__esModule = true;
var message = "Hello Chandan...!";
console.log(message);
var name = 'Chandan';
var lang = "typescript";
var num = 100;
var sentence = "Hey, my name is " + name + "\nand I am learning " + lang;
console.log(sentence);
console.log("first char is " + name[1]);
//num.toPrecision(1);
var myname = null;
var myArray = [1, 2, 3, 4];
console.log("array is : " + myArray);
var mytupple = ['Chandan', 1987];
console.log("name : " + mytupple[0] + ", YOB : " + mytupple[1]);
var random = "Vedansh";
console.log(random.toUpperCase());
console.log(random.toUpperCase());
//console.log(random.name);
var newRandom = "Puggal";
console.log("Surname is " + newRandom);
newRandom = 10;
console.log(newRandom.toPrecision(10));
//onewRandom.
